services:
  php-fpm:
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    environment:
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
    volumes:
      - ..:/var/www:rw
    networks:
      - network_bridge

  nginx:
    build:
      context: ./nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ..:/var/www:rw
    depends_on:
      - php-fpm
    networks:
      - network_bridge

networks:
  network_bridge:
    driver: bridge