services:
  openswoole:
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - PUID=${PUID:-1000}
        - PGID=${PGID:-1000}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG:-false}
    environment:
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=localhost}
    ports:
      - "${APP_PORT:-9501}:9501"
    volumes:
      - ..:/var/www:rw
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge